plugins {
    id 'groovy'
}

group = 'pl.olafcio.limepublish'
version = '1.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.0.8'

    compileOnly gradleApi()

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

base {
    archivesName = "lime-publishing"
}

test {
    useJUnitPlatform()
}
