package pl.olafcio.limepublish.enums

enum Environment {
    CLIENT_AND_SERVER,
    CLIENT_ONLY,
    CLIENT_ONLY_SERVER_OPTIONAL,
    SINGLEPLAYER_ONLY,
    SERVER_ONLY,
    SERVER_ONLY_CLIENT_OPTIONAL,
    DEDICATED_SERVER_ONLY,
    CLIENT_OR_SERVER,
    CLIENT_OR_SERVER_PREFERS_BOTH,
    UNKNOWN
}
